name: Get Info

on:
  workflow_dispatch:
    inputs:
      tag:
        description: TAG
        required: true
  release:
    type: [published]
  push:
  
jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: tags
        id: tags
        run: |
          if [[ -n "${{ github_ref }}" ]]; then
            echo ${{GITHUB_REF}}
          fi
          if [[ -n "${{ github_ref_name }}" ]]; then
            echo ${{GITHUB_REF_NAME}}
          fi
          if [[ -n "${{ github_workflow }}" ]]; then
            echo ${{GITHHUB_WORKFLOW}}
          fi
          if [[ -n "${{ github_repository }}" ]]; then
            echo ${{GITHUB_REPOSITORY}}
          fi
          if [[ -n "${{ github_ref_type }}" ]]; then
            echo ${{GITHUB_REF_TYPE}}
          fi
          if [[ -n "${{ github_event }}" ]]; then
            echo ${{GITHUB_EVENT}}
          fi
          if [[ -n "${{ github_event_inputs.tag }}" ]]; then
            echo ${{GITHUB_EVENT_INPUTS.TAG}}
          fi
          if [[ -n "${{ github_ref }}" ]]; then
            TAG="${{GITHUB_REF}}
            echo "TAG=${TAG}" >> $GITHUB_ENV
          fi
          echo "##[set-output name=version;]VERSION=Hello"
      - name: print
        run: |
            echo ${{steps.tags.outputs.version}}
        
        
