name: Get Info

on:
  workflow_dispatch:
    inputs:
      tag:
        description: TAG
        required: true
  release:
    type: [published]
  push:
  
jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: tags
        id: tags
        run: |
          echo ${{GITHUB_REF}}
          echo ${{GITHUB_REF_NAME}}
          echo ${{GITHHUB_WORKFLOW}}
          echo ${{GITHUB_REPOSITORY}}
          echo ${{GITHUB_REF_TYPE}}
          echo ${{GITHUB_EVENT}}
          echo ${{GITHUB_EVENT_INPUTS.TAG}}
          TAG="${{GITHUB_REF}}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "##[set-output name=version;]VERSION=Hello"
      - name: print
        run: |
            echo ${{steps.tags.outputs.version}}
        
        
